src/lolex.js
Only throw `Error` about `setImmediate` not being faked, when there is a `setImmediate` function to fake.
Once a new version is baked with this fix, we update `lolex` in Sinon.JS and can fix https://github.com/cjohansen/Sinon.JS/issues/786
=> Fix complaint about missing fake setImmediate

LICENSE, Readme.md, package.json
npm install would yield the warning:
"npm WARN package.json lolex@1.2.2 license should be a valid SPDX
license expression"
The existing license was not exactly one of the BSD licenses. I changed
it to the "revised" BSD 3-clause text which came closest and also
adapted package.json to match.
=> Fix for warning about SPDX license format on npm install

Readme.md, src/lolex.js, test/lolex-test.js
setSystemTime() changes the current time while ensuring that the behavior of any existing timers doesn't change. It simulates the user changing the system clock while the program-under-test is running.
=> Fix for Sinon.JS issue #808: add setSystemTime() function

lolex.js, src/lolex.js
When binding the original native functions to the global object to make them writable in IE, `lolex` assigns setImmediate no matter if it is present as a native browser function or not. That made some polyfills fail, as they would add the polyfill to the _prototype of window_, not the window object itself. Thus, the property added by `lolex` would shadow that of the prototype.
The fix simply checks if the property is present beforeadding it.
Should implicitly fix issue cjohansen/Sinon.JS#821
Verify problem was introduced in 4aec26199f14df8bca46d300811cfcf9ec03ccc3
```
git clone  git@github.com:sinonjs/lolex.git 
cd lolex
curl -o test-script.sh https://raw.githubusercontent.com/fatso83/lolex/setImmediate-shim-bug/test-script.sh
git bisect start v1.2.1 v1.2.0  && git bisect run sh …
```
=> Fix for breaking setImmediate polyfills

script/ci-test.sh, src/lolex.js, test/lolex-test.js
`npm run lint` was failing. These seem to be the minimum changes required for it to be happy. I've tried fixing lint errors in the test file as well but there are two cases however that jslint won't ever be happy about. I've added a comment explaining to comment those out.
Perhaps a different linter should be used?
I've added linting (of the source file) to the CI script to ensure the source stays nice and tidy.
=> Fix lint errors

Readme.md, lolex.js, src/lolex.js, test/lolex-test.js
Rather than ticking by a certain number of milliseconds this method advanced the clock to the first scheduled timer. This is useful when performing fuzz testing on an entire application and you want to trigger a single timer.
I based the tests off of those for `clock.tick()`.
Let me know what you think! :smile:
=> Implement clock.next()

package.json
Could not run `npm run lint` on Windows due to `$(..)` syntax.
=> Remove BASH syntax in lint script

test/lolex-test.js
Add tests demonstrating that a fake Date could be created with one argument as a String since this string is in a format recognized by the Date.parse() method.
=> Add tests about Date creation

.min-wd, .travis.yml
We already have the possibility to run tests in real browsers with `npm run test-cloud`. The prerequisite to be able to run this command is a free SauceLabs account and the `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY` environment variables.
If these environment variables are configured in the Travis config, SauceLabs can be used from there. With this config, we run the `test-cloud` build only once in the node 4.2 build.
I used my SauceLabs account for the purpose of trying this out. We can keep it this way or create a „Sinon“ account which we can share. The access key was encrypted using the method described [in the Travis documentation](https://docs.travis-ci.com/user/encryption-keys/).
The first successful build (from this branch) is here: https://travis-ci.org/sinonjs/lolex/jobs/112401049 …
=> Run test-cloud on Travis

Readme.md, src/lolex-src.js, test/lolex-test.js
This runs all pending timers until there are none remaining. If new timers are added while it is executing they will be run as well.
This makes it easier to run asynchronous tests to completion without worrying about the number of timers they use, or the delays in those timers.
It runs a maximum of `loopLimit` times after which it assumes there is an infinite loop of timers and throws an error.
=> Add runAll method to run timers until empty

Readme.md, src/lolex-src.js, test/lolex-test.js
Add the ability to run to the last currently scheduled timer.
https://github.com/sinonjs/lolex/issues/44
This is useful when you want to run a test to completion, but the test recursively sets timers that would cause `runAll` to trigger an infinite loop warning.
=> Run to last existing timer

src/lolex-src.js
This fixes a bug where Lolex would no longer work in browsers because `process` doesn't exist.
=> Check for existence of `process` before using it

src/lolex-src.js, test/lolex-test.js
The error message given when a timer created by `setTimeout` is cleared by a different type is wrong - the `set* / clear*` types are the wrong way around.
Additionally the test cases for the exceptions are currently not testing the code correctly - currently the error thrown is `Cannot read property 'clock' of undefined` due to the missing bind.
This fixes the error message and tests that its correct for all the combinations.
=> Correct the clear{Interval|Timeout|Immediate} error message when attempting to clear a different type of timer.

src/lolex-src.js, test/lolex-test.js
In Node.js, when setTimeout is called with an time string, it is parsed. If the string is an invalid number, it's assumed as 0. In lolex, using a string as time causes the setTimeout not to trigger the callback function.
This is the behaviour that I would expect:
```js
it("parses no-numeric string times", function () {
this.clock.setTimeout(function () { lolex.evalCalled = true; }, "string");
this.clock.tick(10);
assert(lolex.evalCalled);
});
it("evals non-function callbacks", function () {
this.clock.setTimeout("lolex.evalCalled = true", 10);
this.clock.tick(10);
assert(lolex.evalCalled);
});
```
=> Fix setInterval() behavior with string times

Readme.md
Updates some installation notes. Removes the reference to it being hosted on the Sinon site. Has not been true for quite a while. Also adds some info on using it in a browser.
=> Update installation notes

lolex.js, package.json, src/lolex-src.js
This is a PR for **master**, it is a solution for https://github.com/sinonjs/sinon/issues/1143
The PR fixes compatibility with React Native and quite possibly other libraries.
1. Run test in https://github.com/mroderick/sinon-issue-1143
1. Observe that an error occurs
```
TypeError: Date is not a constructor
at new MessageQueue (node_modules/react-native/Libraries/Utilities/MessageQueue.js:62:26)
at Object.<anonymous> (node_modules/react-native/Libraries/BatchedBridge/BatchedBridge.js:17:19)
at Object.<anonymous> (node_modules/react-native/Libraries/Utilities/RCTLog.js:14:19)
at setUpConsole (node_modules/react-native/Libraries/JavaScriptAppEngine/Initialization/InitializeJavaScriptAppEngine.js:54:1)
```
1. Check out this PR, switch into that folder
1. `npm link`
1. Switch back to your …
=> Fix sinonjs/sinon#1143: Only overwrite globals when running in IE

src/lolex-src.js
Error would previously say `"Aborting after running 1000timers, assuming an infinite loop!"` (notice the lack of space between `1000` and `timers`). Adding a space there.
Fixes #93.
=> Fixed typo in clock.runAll error

.travis.yml
This PR configures Travis CI to use node 4, 6 and 8 (LTS versions)
=> Run tests in node 4, 6, 8 on Travis CI

Readme.md, lolex.js, package.json, src/lolex-src.js, test/lolex-test.js
This pull request adds support (and tests) for `performance.now` in browser envrionments.
Fixes https://github.com/sinonjs/lolex/issues/82
=> Add support for performance.now

src/lolex-src.js, test/lolex-test.js
As shown in #102, something as simple as adding one additional configuration option becomes unmanageable due to the current design of a "telescoping method signature" where all the arguments are optional. This makes contributors reach for alternate ways of configuring lolex, such as adding flags on the object.
I propose we change the signature to accept a single configuration object with named parameters to simplify this. This PR is that proposal implemented. There are also [many other pros to constructor-like functions](https://gcanti.github.io/2014/09/25/six-reasons-to-define-constructors-with-only-one-argument.html) like this of 1-arity.
This is a breaking change and will require a new major version.
=> Change lolex.install signature

src/lolex-src.js, test/lolex-test.js
There is an issue with `tick()` when `setSystemClock` is called in a timer, and then that same timer throws an error. The correction that `tick()` does to account for `setSystemClock` happens within the try catch block, and not after it. If an error is thrown then this check is skipped.
The included unit tests demonstrate the issue.
=> Fix issue with tick(): setSystemClock then throw

src/lolex-src.js
I might not understand what that code does - but it looks like leftoff from previous versions of the code. 
I see no case in which there is an exception and it's not thrown - and the `if` seems redundant at which point we might as well avoid the try/catch.
=> Remove try/catch that captures exception

src/lolex-src.js, test/lolex-test.js
Error on incorrect install use of lolex 2.
Fixes https://github.com/sinonjs/lolex/issues/108
=> error on incorrect install use

.gitignore, Readme.md, src/lolex-src.js, test/lolex-test.js
resolves #126 
- does not fake process.nextTick by default
- added .idea folder to .gitignore
- added missing clock teardowns after installs
=> issue #126 - do not attach `nextTick` by default

src/lolex-src.js, test/lolex-test.js
i did not change the logic for handling `setTimeout` with a value which is smaller than 1. I think this is redundant since some users might be using `setTimeout` with a value of 0, then `tick()`ing it might result in an unexpected sequence of timers being executed. There's one test that demonstrates this (`"calls the given callback before setTimeout"`).
not sure if we need to change this edge case.
=> issue #67 - overflowing the timer correctly according to int32_t

Readme.md, lolex.js, src/lolex-src.js, test/lolex-test.js
I could really use a mocked `requestAnimationFrame` for some testing I'm doing, so I thought I'd take a crack at adding it here. I opted to just tick a rAF every 16ms, so the callbacks can just be run with `clock.tick(16)`. I think this mostly works / does what's needed, but I'm not sure of a few things, like bootstrapping this only in a browser or passing in the correct value for the callback arg. Let me know if I'm on the right track.
=> Add support for requestAnimationFrame

package.json, src/lolex-src.js
Also adds --check-leaks flag to mocha test runs.
Fixes #142
=> Stops leak of (request|cancel)AnimationFrame into global scope.

.npmrc, .travis.yml, package-lock.json, package.json
To avoid future situations like https://github.com/sinonjs/sinon-test/pull/85, we should freeze dependencies.
This won't really save our bacon for old node versions, but it's a start
=> Freeze dependencies

Readme.md
I _think_ this is correct.
It would be great if I was able to pass `true` or `'all'` or something, so that I can get all future added timers for free even though I opt in to fake `nextTick`.
It seems like methods are only added if  they exist in the original global, even though they are specified in `toFake`. Is this understanding correct? Should it be clarified in the docs either way?
=> Add missing functions in default `toFake`

package.json
This prevents unnecessary files to be published to the npm registry, saving bandwidth and speeding up installs for everyone.
```text
du -h lolex-2.3.1.tgz
108K	lolex-2.3.1.tgz
```
```text
du -h lolex-2.3.1.tgz
20K	lolex-2.3.1.tgz
```
With [~4.6M downloads/month](https://www.npmjs.com/package/lolex), this will save `4,600,000 * 88,000 / 1024^3 = ~376GB/month`
1. `npm pack`
1. Expand the package
1. Observe that `lolex.js` is in root, and that `src/` still contains `lolex-src.js`
=> Add files section to package.json to avoid unnecessary package bloat

src/lolex-src.js, test/lolex-test.js
See this issue in Jest, with links to spec: https://github.com/facebook/jest/issues/5960. Without changing the implementation of Lolex, Jest test suite breaks when attempting to use it
=> handle negative infinity timeout

src/lolex-src.js
Ref #167, but it's not enough. With this change, Jest fails with an internal JSDOM error...
Looks like the same error as the one from IE in #167, so fixing that will probably fix Jest as well
=> Access `Performance` via `_global`

.travis.yml, package-lock.json, package.json, script/ci-test.sh, src/lolex-src.js
It turned out that some properties on the `Performance` property are not writable in Chrome. I'm a little surprised this wasn't reported by users yet.
Even though the Travis build fails due to puppeteer installation issues, you can verify locally that this change makes upgrading to Mochify v5 possible.
Maybe related: #158
Update: Running `npm run test-cloud` also works, verifying that tests pass in IE 9, 10, 11 and Firefox.
=> Upgrade Mochify to v5.6

integration-test/.eslintrc, integration-test/lolex-integration-test.js, package-lock.json, package.json, src/lolex-src.js
Includes both #162 and #168, plus an integration test using JSDOM.
~~This doesn't really work though, as `window.performance` is `readonly` in JSDOM. This matches the spec (or, at least it matches the text on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Performance)), but it does not match the behavior of Chrome.~~
~~The second commit skips faking `performance`, and the test passes. I don't like that, though.~~
`window.performance` is `readonly`, so instead of using simple assignment, this PR uses `Object.defineProperty`.
=> add simple integration test with jsdom

package.json
This avoids running `bundle` on `npm install`, meaning it's less likely to be included in PRs. It also removes the warning: 
https://docs.npmjs.com/misc/scripts#prepublish-and-prepare
=> chore: use `prepublishOnly` instead of `prepublish`

integration-test/lolex-integration-test.js, src/lolex-src.js
This was discovered by @mjesun when trying to apply a version of Jest with Lolex at Facebook.
I'm not sure what the solution should be. Our idea was to just assign the `prototype`, but it is already copied
=>  Access Date on `_global`

src/lolex-src.js
`clock.timers` is used everywhere as an object and initializing in all other places as an object. So here it's a bug that is not affecting the functionality because of nature of JS but confuses the source readers
=> fix clock.timers initialization from array to object

src/lolex-src.js, test/lolex-test.js
Fix issue #191 
According to NodeJS documentation the ref() and unref() return the timer.
https://nodejs.org/dist/latest-v8.x/docs/api/timers.html#timers_timeout_ref
This PR fixes it in lolex. Relevant tests are added.
After fix it prints the correct timer:
```js
const lolex = require("./src/lolex-src");
const clock = lolex.install();
const timer = setTimeout(() => {}, 5000).unref();
console.log(timer);
// Prints: { id: 1, ref: [Function: ref], unref: [Function: unref] }
```
=> Fixes ref() & unref() return value on NodeJS

src/lolex-src.js
While trying to run a test suite with fake timer in iOS 9.3, I discovered an issue with lolex: `window.performance` cannot be replaced using `Object.defineProperty` because its descriptor has `configurable: false`. However, assigning a new value works.
Also happens to fix #190.
I first tried checking on the descriptor `configurable` property which fixed the issue. It turned out that simply replacing the property works as well, but I recalled that `Object.setProperty` was introduced in #169 by @SimenB to fix it in JSDom. However, all tests pass and I'd like to have confirmation by a JSDom expert that this change doesn't re-introduce the issue.
I can reproduce the issue with the lolex test suite:
```bash
$ node_modules/.bin/mochify --consolify test.html
$ http-server .
```
and then open …
=> Fix performance replacement on iOS 9.3

integration-test/lolex-integration-test.js, package-lock.json, package.json, test/lolex-test.js
```
$ npm audit
=== npm audit security report ===
found 13 vulnerabilities (10 low, 2 moderate, 1 high) in 5632 scanned packages
run `npm audit fix` to fix 12 of them.
1 vulnerability requires manual review. See the full report for details.
```
```
$ npm audit
=== npm audit security report ===
found 0 vulnerabilities
in 5632 scanned packages
```
=> Update insecure dependencies

src/lolex-src.js, test/lolex-test.js
Fix issue #201 by always parsing the `timeout` argument of `setInterval` to an integer value, so that strings are possible.
See Description in #201 
As suggested by @fatso83, the argument is now parsed to an integer value (`parseInt()`).
There is also a test proving that a string input works.
=> fix(setInterval): parse `timeout` arg to integer

src/lolex-src.js, test/lolex-test.js
Fixes issue #200 by overriding methods on window.performance
Could not see any reason why to keep the initial implementation delegated to the original
object, so overrode them with no-ops. Input on why this might not be the right way
to deal with this?
=> Fix issue 200: performance.mark triggers TypeError

src/lolex-src.js, test/lolex-test.js
The changes introduced for 2.7.3 did not break anything, but it introduced a new test that showed
bugs in the existing implementation by actually running `performance.mark()`.
Also, trying to run performance.mark failed on Safari 9, as it has `performance.now`, but
not `performance.mark`. We therefore needed an additional guard before those tests.
We didn't see the fail until merging to master due to pull requests not running the Sauce Labs
tests, and me being too forgetful and impatient to wait for the tests 😀
The changes can be split into two
- changes in the test code to avoid running a test in Safari 9
- changes in the library that deals with IE 10 and IE 11
The prototype for `Performance` in Internet Explorer is not a function like
everywhere else, so we needed to expand the test for …
=> Fix cloud tests for IE and Safari :hankey:

src/lolex-src.js, test/lolex-test.js
Improve [sinon#1852](https://github.com/sinonjs/sinon/issues/1852) issue by adding an explicit error message.
When using `webpack` and `jsdom` together, the global context doesn't have a `Date` object and `lolex` will fail with a really confusing error: `TypeError: Cannot read property 'now' of undefined`.
This problem is easily triggered when using `sinon.useFakeTimers` (which relies on `lolex`) in this setup.
This PR adds an explicit exception when no `Date` are present in the global context.
The message contains a link to @mroderick's comment that explains how to get around the problem. (Maybe this would be better as a wiki page?)
The check is placed in `createClock` (which means it's triggered by `install` as well) instead of right when `NativeDate` is initialised so it doesn't crash …
=> Add an error when creating a clock with no Date object

src/lolex-src.js, test/lolex-test.js
Without the code change, the added test makes node hangs forever until it runs out of memory.
`clock.tick` expect the argument to be how many millis it should tick. Currently, we pass it the timestamp of when it should be done ticking.
https://github.com/sinonjs/lolex/blob/1278eaade7da311d203fc6c33f67f85c828a09f2/src/lolex-src.js#L723
I don't understand how no-one hit this bug for 2.5 years... It's been that way since the original implementation: #50.
Subtract the current time on the clock before calling `tick`. The first thing tick does is add it back, so it knows when to stop.
https://github.com/sinonjs/lolex/blob/1278eaade7da311d203fc6c33f67f85c828a09f2/src/lolex-src.js#L603
We might want a `tickTo` method? Implementation would be `this.tick(to - clock.now)`, so maybe not valuable.
=> fix: runToLast should respect current time

src/lolex-src.js, test/lolex-test.js
=> fix: handle floating point in hrtime

RELEASE.md, package.json, scripts/postversion.sh, scripts/preversion.sh, scripts/version.sh
Releasing is tedious. This is faster.
Simplifies the release process into `npm version patch && npm publish`
One point that might be worth noting (changing?) is that at no point
are we running the cloud tests. This is only usually done on the master
branch, but we have had times where the maintainer has been a bit too
quick and haven't waited for the `master` branch to build before
releasing a new version.
Should we include a `postversion` step where we run the `test-cloud`
script? All maintainers should by now have access to the sauce labs
credentials.
=> Make releasing a new  version a 2 step process

Readme.md, src/lolex-src.js, test/lolex-test.js
This is a fix for #207, which dealt in round-off errors. 
Other notable changes are:
- removes `clock.hrNow`. Should not be an issue as it's an internal detail not documented in our API
- throws on negative ticks. This is a breaking API change, but I would be very surprised if it affected anyone, as this essentially means backwards time travel.
- change some test structure, replacing `if()` blocks with conditional `this.skip()`
This PR fixes #207 by doing away with floats for representing time; opting to store milliseconds and millisecond decimals separately. We could have avoided the complications of storing two parts by opting to store all ticks as nanoseconds, but that would pose other round-off issues when adding/subtracting high-value milliseconds. Javascript is unable to represent …
=> Introduce nanosecond precision ticks

src/lolex-src.js, test/lolex-test.js
Adds support for queueMicrotask added in Node.js 11 https://github.com/nodejs/node/pull/22951
Browsers should also eventually add this. 
This is also not urgent since Node.js 11 isn't even out yet.
This is essentially a nextTick that drops arguments which we already support.
=> add support for queueMicrotask

src/lolex-src.js, test/lolex-test.js
For a start and be able to move on with your help I added this tests:
**requestIdleCallback**
- throws if no arguments
- returns numeric id
- returns unique id
**cancelIdleCallback**
- removes idle callback
I tried figured out the behaviour and make busy system to see what is going on. This is what I got:
------------------ – new interval in setInterval (40ms)
idle without timeout - requestIdleCallback task without timeout option
idle with timeout - requestIdleCallback task with timeout option
timeout - three setTimeouts (10ms, 20ms, 30ms).
There are three idle tasks in each interval two without timeout and one with 15ms timeout.
Serial numbers used for the idle tasks.
Log:
```
requestIdleCallback.js:41 ------------------
requestIdleCallback.js:43 idle 1 without timeout …
```
=> [WIP] Issue #218 – `requestIdleCallback` implementation

src/lolex-src.js, test/lolex-test.js
Hello, guys.
I did a quick fix for #232 not faking this method by default like `nextTick`, but have a couple of questions.
`--trace-warnings` point on `_global.queueMicrotask` usage in the code.
There are two places in the code:
1. Feature detection (I fixed in @ehmicky way). Not sure about that, because it gives `true` when property value is `null` or `undefined`. What do you think?
2. And when it stores in `lolex.timers`. What is the purpose of storing all the timers methods that supported by particular environment there instead of storing only just list of them? As I got from the code `hijackMethod` assign `_queueMicrotask` to `_global.queueMicrotask`, but not to `timers.queueMicrotask`. I might be incorrect.
Now it is giving warnings only with `lolex.install({ toFake: …
=> [WIP] queueMicrotask() ExperimentalWarning in Node

src/lolex-src.js, test/lolex-test.js
Fix issues caused by applications which expect `performance.getEntries`, `performance.getEntriesByName`, and `performance.getEntriesByType` to return arrays (such as Facebook SDK - downstream issue: cypress-io/cypress#3625)
Right now, lolex clobbers these with `() => undefined`. Just using `() => []` instead would fix this.
MDN page for Performance functions: https://developer.mozilla.org/en-US/docs/Web/API/Performance
Only 5 have non-undefined return types. The other 2 (besides `getEntries.*`) are:
* `now()` - already done by lolex
* `toJSON()` - not handled, not sure if there's a good way to mock this value
Just have those 3 methods return `[]` when `lolex.install()` is called, instead of `undefined`
=> Return empty arrays for performance.getEntries, other relevant methods

integration-test/lolex-integration-test.js, lolex.js, src/lolex-src.js
Fix #243 by changing the way the `performance` field gets overwritten
JSDOM has a read only `performance` field.  So, when JSDOM is configured to provide [global values](https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md), lolex will error on init. This is because it can't overwrite the global `performance` field.
=> Fix support for replacing the JSDOM performance field

integration-test/lolex-integration-test.js, lolex.js, src/lolex-src.js
Fix #243 by changing the way the `performance` field gets overwritten.  This time without breaking some browsers.
JSDOM has a read only `performance` field.  So, when JSDOM is configured to provide [global values](https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md), lolex will error on init. This is because it can't overwrite the global `performance` field.
=> Fix jsdom 2

src/lolex-src.js, test/lolex-test.js
Serves as a fix for sinonjs/sinon#2086
=> Avoid installing setImmediate in Chrome

src/lolex-src.js, test/lolex-test.js
A continuation of the work in #268; this basically fixes the additional clock tests @mantoni added in sinonjs/sinon#2086
See sinonjs/sinon#2085. Sinon/Lolex installs setImmediate even when this isn't present. The global install has been removed in #268, and this continues that thread by also avoid creating it in the clock and not running any tests involving setImmediate.
=> Don't create setImmediate in clock if unsupported 

integration-test/lolex-integration-test.js, package-lock.json, package.json, src/lolex-src.js, test/lolex-test.js
This PR replaces #262, as dependabot doesn't know how to upgrade when new dependencies are needed.
* Upgrade and add related plugins and configs
* Fix/disable lint violations
=> Upgrade eslint, add prettier

README.md, package.json, src/lolex-src.js, test/lolex-test.js
This is a rebased and updated version of #105.
I still have to do a full review and test in our code base, probably might need to update some documentation, but just wanted to open this up. I probably also need to re-read all the threads on this... But hopefully this is now closer to getting merged than it was before :)
=> Upgrade lolex with async versions of all timer-executing calls (2019)

src/lolex-src.js
Fixes #272 which was introduced by #270.
Inspect the result of bundling this branch here: https://jsbin.com/godesuduxo/edit?html,js,console
The `global` variable is not provided by Browerify anymore. I don't fully understand why this isn't caught by test runs in browsers yet. Will need to investigate further.
Use the `_global` variable which is set to `window` in browsers.
=> Fix global ReferenceError

.gitignore, package-lock.json, package.json
This PR adds tasks for calculating coverage (`test-coverage`) and to check coverage (`test-check-coverage`).
This paves the way for putting this project in line with the other Sinon projects and get us to 100% test coverage.
1. `npm ci`
1. `npm run test-coverage`
1. Observe a nice coverage report
1. Modify the tolerances for coverage in `package.json`, set a value higher than the measured coverage
1. `npm run test-check-coverage`
1. Observe that there is an error displayed
1. Observe that there was a non-zero exit code (`echo $?`)
1. `git reset --hard`
1. `npm run test-check-coverage`
1. Observe that there is no error displayed
1. Observe that a zero exit code (`echo $?`)
=> Test coverage: use nyc

.eslintignore, .github/ISSUE_TEMPLATE.md, README.md, RELEASE.md, fake-timers.js, integration-test/fake-clock-integration-test.js, package-lock.json, package.json, scripts/postversion.sh, scripts/version.sh, src/fake-timers-src.js, test/fake-timers-test.js
This PR renames the package to `@sinonjs/fake-clock`.
It was suggested that we rename this package to have a less confusing name (I can't recall who suggested it, or in which communication channel).
I will soon be doing a larger effort in improving the documentation of Sinon and associated libraries. I thought it would be beneficial to that effort to get the rename of packages out of the way first.
See https://github.com/sinonjs/sinon/issues/1651
1. Rename repository
1. Merge this branch
1. Bump the major version
1. Publish the renamed package to `npm` registry
1. Deprecate the `lolex` package in the `npm` registry
1. Update `sinon` to use the new package
1. (this repo): `npm ci`
1. (this repo): `npm link`
1. (sinon repo): `npm link @sinonjs/fake-clock`
1. (sinon …
=> Rename package to @sinonjs/fake-clock

src/fake-timers-src.js
When running `npm run test-cloud`, the tests would fail in IE11.
In 4cdc47d8e0876ca38d0497e8f358ef9e4a643bf7 the code inserted here was
removed, as it was thought to not be necessary. For whatever reason,
this code is depended on for the tests to be set up correctly in IE11.
Putting the code back fixes the tests.
1. `npm ci`
1. `npm run test-cloud`
1. Observe that tests pass in all browsers tested
=> Fix failing tests in IE11

src/fake-timers-src.js, test/fake-timers-test.js
Fixes #223, similar to what we did for [`jest-fake-timers`](https://github.com/facebook/jest/pull/9180/files).
Noticed after starting there's already https://github.com/sinonjs/lolex/pull/227, but that seems stale and I'm not sure what some of the changes are for.
I'll do what I can to incorporate any review comments and get this through! :sweat_smile: 
If there's consensus that [storing a `global.Promise` backup](https://github.com/sinonjs/lolex/pull/227/files#r233684110) is a good idea, can do that, but would do another PR first, changing this in existing code.
=> support util.promisify in Node

integration-test/fake-clock-integration-test.js, package-lock.json, src/fake-timers-src.js, test/fake-timers-test.js
Removes `config.target`, simplifying the API by
only making it possible to choose alternate targets
using `withGlobal(target)`.
See discussion in #276 and sinonjs/sinon#2156
=> Remove config.target

src/fake-timers-src.js, test/fake-timers-test.js
Fix issue #315 by checking if `timer.delay` is a number. If it isn't make it one by parsing it to an integer.
=> Convert timer delay to number if not already

src/fake-timers-src.js, test/fake-timers-test.js
Allowing `clearTimeout` to clear `setInterval` and `clearInterval` to clear `setTimeout`, 
as this is possible by HTML Living Standard.
Issue #304  
Tests were altered to match the new changes :)
=> issue #304 fix

src/fake-timers-src.js, test/fake-timers-test.js
Fix issue #187 by adding an actual implementation to `refresh()`.
Previously, `refresh()` was added to the timer API as an alternative to manually resetting timeouts via `clearTimeout()` and `setTimeout()`. However, while the interface itself was added, it remained a no-op function. This is confusing, since the presence of this function creates the expectation that the timer has been refreshed when it actually hasn't.
`refresh()` now clears the existing timeout and generates a new one with the same function and delay parameters, but a new ID.
=> Support timeout.refresh in node environments

src/fake-timers-src.js, test/fake-timers-test.js
Fix issue #230 by using stack information for jobs and timers to provide more context when an infinite loop error is thrown.
This solution works by adding a `stack` property to jobs and tasks. This data can then be used, if an infinite loop is detected, to set the stack of the thrown `infiniteLoopError`.
```
Error: Aborting after running 5 timers, assuming an infinite loop!
Timeout - recursiveCreateTimerTimeout
at recursiveCreateTimer (test/fake-timers-test.js:4668)
at recursiveCreateTimerTimeout (test/fake-timers-test.js:4669)
at callTimer (src/fake-timers-src.js:441)
at Object.next (src/fake-timers-src.js:1039)
at src/fake-timers-src.js:1128
```
=> Add stack trace to code recursively scheduling timers

fake-timers.js, src/fake-timers-src.js, test/fake-timers-test.js
This is the first step (out of 3) in solving issue #319.
The use of `eval()` will eventually not be canceled, and this pull request tricks Rollup to not throw an error when `eval()` is used.
=> Fixing issue #319 - preventing Rollup eval error

fake-timers.js
This repository doesn't use the `no-prototype-methods` rule that is
managed with `local-rules` plugin, so the comments make no sense.
ESLint should really throw an error here...
1. search the codebase for `local-rules`
1. Observe that there are no results
=> Remove misleading comment

.gitignore, package-lock.json, package.json, tsconfig.json
In order to improve the experience of TypeScript users, we are compiling
`.d.ts` files from the JSDoc and distributing them with the package
This PR drops the bundled version, as we believe that to be entirely unnecessary.
* We'd like to ship the library with `.d.ts` files, to allow improved experience for TypeScript users
* Create `.d.ts` files from the source files
1. `npm ci`
1. `npm run build`
1. Observe that there are `.d.ts` files in the `types/` folder
2. `npm pack`
3. Observe that the `.d.ts` files are included in the package
4. `npm link`
5. In a `sinon` checkout:
1.  `npm link @sinonjs/fake-timers`
2. `npm test`
3. Observe that tests still pass
=> Publish .d.ts files

src/fake-timers-src.js
Fix inconsistent use of `Object.keys` and `keys` polyfill.
While considering how to implement `Object.assign`, I noticed that `Object.keys` is used in some places and the `keys` conditional polyfill is used in others.  This intent is unclear (although after reviewing the history I assume it was left over from previous compatibility requirements) and it seemed to present needless complexity and maintenance burden.
The current [sinon compatibility] specifies that "the source is written as ES5.1", which defines [Object.keys].  This PR replaces the two remaining uses of the polyfill and removes it to reduce.
If there is reason to keep the polyfill, I could send a PR to use it everywhere, move it to [commons](https://github.com/kevinoid/commons), and/or add comments to explain why the use is …
=> Remove Object.keys polyfill

README.md
In 7f56133373b240a397b00210c6b22c64d8ca8154 we removed the bundled
version, but failed to update instructions for use in browsers.
=> Update README section about browser use

package.json, scripts/preversion.sh
We don't need to run all the tests all the time. With CI we get fast feedback and prevent accidental merging of bad branches
This removes some of the frustrating parts of working in this library.
=> Simplify pre-commit hook

README.md
The `target` option was removed in #318. We remove all mentions of this option from the readme and replace it with `withGlobal`.
=> Remove mention of `target` from readme

src/fake-timers-src.js
We make the configuration argument for `install` and all configuration properties optional in the TypeScript definition. This fixes #352.
As described in #352, the type definitions generated from the JSDoc comments required the config object with all parameters when calling `install`. All of these parameters are optional however.
It was necessary to create a JSDoc `@typedef` section because TypeScript is not able to generate the intended types from
@param [config.now] {number|Date}
=> Make config properties optional in TypeScript defs

README.md
Add notice for typescript users on the breaking changes in the UX.
See https://github.com/sinonjs/fake-timers/issues/352
=> Add notice on breaking changes to TypeScript users

README.md
New incomplete typings distributed with version 7 will be selected by typescript. That breaks projects. Add recipe how to guide typescript to select typings from DefinitelyTyped.
* See https://github.com/sinonjs/fake-timers/issues/352#issuecomment-762318145
=> Add docs about typings

.editorconfig, .github/CONTRIBUTING.md, README.md, package.json, src/fake-timers-src.js
This is more secure. Also the inconsistency when running `yarn outdated`  bugged me.
Replace all `http://` URLs with `https://`. I verified all changed URLs work with https.
=> Change the protocol for all URLs to https://

src/fake-timers-src.js, test/fake-timers-test.js
Refresh wasn't forwarding the arguments passed to setTimeout.
Fixes #368
=> Fix refresh arguments forwarding

src/fake-timers-src.js
Continued from #370.
I've tried to do the following:
* Depend on `globalThis`, such that things like `setTimeout` are strongly typed as being identical to `typeof globalThis.setTimeout` - this should theoretically mean you get the right types depending on the environment you're in (node, browser)
* Define node-specific functions ourselves to avoid pulling node types in
* Define what `timers`
* Add jsdoc to `withGlobal` but _not_ a return type (so typescript will infer it)
If someone can double check that depending on the global types makes sense and will work fine, that'd be much appreciated. It seems to for me
cc @fatso83
=> Add further stronger typing and depend on globalThis

.circleci/config.yml, .eslintrc.yaml, package-lock.json, package.json, test/fake-timers-test.ts
https://github.com/sinonjs/fake-timers/issues/356#issuecomment-768227159
I just added a dummy test, no attempt at coverage. But it's a good opportunity for new contributors if they want, and future changes to the types should include tests
=> chore: add type tests

.min-wd
- Drop IE11 and Safari 9 per discussion in #375 and sinonjs/sinon#2359.
- Also copies in browsers from the mother Sinon repo to include Edge and Safari latest
See discussion in #375 and sinonjs/sinon#2359
=> Drop IE11 and Safari 9 from Sauce Labs test runners

src/fake-timers-src.js
This improves the generated .d.ts so that createClock may be called without arguments.
Improve .d.ts types for `createClock()` so that it's possible to call it from TypeScript without arguments.
The currently generated .d.ts uses JSDoc, which incorrectly specified the two arguments for `createClock()` as mandatory.
=> Fix JSDoc for createClock

src/fake-timers-src.js, test/fake-timers-test.js
Fix #347 by copying symbol own-properties to installed methods.
The `for...in` loop used to copy properties only copies string own-properties to installed methods, which omits [`util.promisify.custom`](https://nodejs.org/api/util.html#util_custom_promisified_functions) necessary for [`util.promisify`](https://nodejs.org/api/util.html#util_util_promisify_original) support on Node as added in #292.
This PR copies all own-property descriptors to get both `Symbol` own-properties and to copy any getters/setters that may be added in the future.
If there's a reason getters/setters should not be copied, let me know and I can add an `Object.assign` polyfill to [sinonjs/commons](https://github.com/sinonjs/commons) and use that instead.
Thanks for considering,
Kevin
Fixes: #347
=> Copy all property descriptors to installed methods

.eslintrc.yaml, package-lock.json, package.json, src/fake-timers-src.js, test/check-types.ts, test/fake-timers-test.js
Update fake-timers to use latest @sinonjs/eslint-config
Was unable to write ES2015+ syntax, even though it should have worked. Also found lots of config I do not think is needed.
Removed all errors. Still 129 eslint warnings remaining - all concerning either missing jsdoc or errors in the types
=> Update eslint config

src/fake-timers-src.js, test/fake-timers-test.js
Re-adding the reverted merge - Add stack trace to code recursively scheduling timers #325 
I've cherry-picked commits made by @alistairjcbrown to re-file the original PR that was merged and then reverted due to some compatibility issues.
=> Retry - Add stack trace to code recursively scheduling timers #325 

src/fake-timers-src.js, test/fake-timers-test.js
Remove implicit dependency on `*Interval` functions in the shouldAdvanceTime feature.
See #390
=> Issue 390 implicit dependencies on faking interval

.github/workflows/main.yml
=> chore: run CI on PRs from forks

src/fake-timers-src.js
This is for #398 which I think we should land and release as 8.0.1. Guards against the error and falls back to the behavior of v7
=> fix: handle missing stack when throwing recursion errors

.eslintrc.yaml, package-lock.json, package.json
I didn't know we had prettier set up (https://github.com/sinonjs/fake-timers/runs/3673842832?check_suite_focus=true) - it's better to just run it as part of `eslint` both for `eslint --fix` and the pre-commit hook. And my IDE will now autoformat on save 🙂 
Note that we can probably remove the `prettier --check` thing as `eslint` will now report any formatting errors.
Negates the need for #402
=> chore: run prettier as part of eslint

CHANGELOG.md
The naming convention for DefinitelyTyped packages for namespaced packages is a bit obscure, so being explicit is nice (even if `tsc` does give the same hint).
=> CHANGELOG: give a hint about how to get type defs

.github/workflows/main.yml, src/fake-timers-src.js, test/fake-timers-test.js
Fixes `performance` on Node 16 which has a global `performance` but not a global `Performance` 
cc @fatso83 @SimenB @itayperry
=> fix global performance node 16

.github/workflows/main.yml
I assume the purpose is to always run on an LTS version of node here. So specifying `lts/*` does the same thing, but does not have to be updated when v18 (and v20 etc) becomes LTS
=> chore(ci): do not hard code node versions

src/fake-timers-src.js, test/fake-timers-test.js
add refed attribute to the res object
-----
add this as required in the issue - Missing hasRef for Node #408
=> add hasRef

package-lock.json, src/fake-timers-src.js, test/fake-timers-test.js
`timer.refresh` looks completely broken to me (and is definitely at least _somewhat_ broken, see https://github.com/facebook/jest/issues/12527).
1. It uses global `setTimeout` and `clearTimeout`, instead of the ones defined in the `global` passed in
1. it (tries to) remove the old timer and schedule a new one, "changing" its ID. This:
1. Does not remove the existing one, as that's not an actual real timer
1. Break identity since we "schedule" (actually, for real, schedules) a _new_ timer instead of refreshing the existing one (try `timer.refresh` in node - `Symbol`s `asyncId` and `triggerId` never changes, only `_idleStart`. also `t.refresh() === t`)
=> fix(timer.refresh): should just change `callAt`

.github/workflows/main.yml, package-lock.json
This PR drops support for Node 12 and adds support for Node 18
See https://nodejs.org/en/about/releases/
=> Drop node 12

test/fake-timers-test.js
Fix issue #441 by fixing a spelling error
See #441. Node 18.8 seems to have the `writable` prop of the Performance fields set to `false` by default and our test did incorrectly try to re-configure it.
=> Fix #441: update spelling of prop descriptor prop

src/fake-timers-src.js, test/fake-timers-test.js
- feat: add test for issue #450
- fix(runToLastAsync): tick the correct amount of time
Fix #450 
In the `runToLastAsync` method, wait the correct amount of time with `tickAsync`
=> Fix(runToLastAsync): Prevent infinite loop

.eslintrc.yaml, .husky/pre-commit, package-lock.json, package.json, src/fake-timers-src.js, test/fake-timers-test.js
=> Upgrade dependencies

package-lock.json, package.json
https://github.com/sinonjs/fake-timers/pull/440#discussion_r1030602932
=> chore: remove `fsevents` dependency

README.md, src/fake-timers-src.js, test/fake-timers-test.js
Closes #452 by creating the `clock.jump(time)` method enabling skipping forward in time and running any timers at most once.
=> Add clock.jump method

CHANGELOG.md, src/fake-timers-src.js, test/fake-timers-test.js
Solve the breaking of timer-dependant methods on the Intl global object by including a mocked version
Even after calling install(), the Intl.DateTimeFormat() class will currently use the real time of the system, not the time specified by the fake clock.
Affected methods: DateTimeFormat.format(), DateTimeFormat.formatToParts()
My repo demonstrating the problem, using Jest (which uses sinonjs/fake-timers): https://github.com/BenIsenstein/jest_fix_intl_fake_timers
The fix works by following the patterns used to mock the global Date class and mocking the Intl object. A producer function is written to return an Intl object largely identical to the original, except for the DateTimeFormat() class. DateTimeFormat has several methods that are time-sensitive, and depend on the system time when no …
=> feat: mock intl api

src/fake-timers-src.js
We no longer support Internet Explorer, so remove those hacks.
=> Remove IE specific hacks

src/fake-timers-src.js
Fix issue #420 by favoring the constructor of the performance instance over the Performance class
jsdom also patches the `Performance` class and doesn't implement all of the methods.
I could not use the workaround mentioned: https://github.com/sinonjs/fake-timers/issues/394#issuecomment-1021665619 because I'm using vitest with jsdom as the environment.
This simply favors the prototype of the performance instance, since that seems to be untouched by jsdom.
=> favor the constructor of the performance instance if it exists

src/fake-timers-src.js, test/fake-timers-test.js
PR #474 has introduced a mock for the intl API, and this has introduced a regression for me, where I'm not able to call `Intl.RelativeTimeFormat`.
The problem showed in some of my test cases, once I updated `fake-timers`, when trying to use `Intl.RelativeTimeFormat` I got the following error: `Intl.RelativeTimeFormat is not a constructor`
The solution I opted for is to assign `RelativeTimeFormat` to the mocked `Intl` API with.
```js
ClockIntl.RelativeTimeFormat = NativeIntl.RelativeTimeFormat;
```
=> feat: add RelativeTimeFormat to Intl API

src/fake-timers-src.js
Fix typescript error T1100 which complains about invalid use of term 'arguments' in strict mode.
Use args instead of arguments in annotation.
=> fixes invalid use of arguments in strict mode error

src/fake-timers-src.js, test/issue-483-test.js, test/issue-async.test.js
Fix the async time forwarders that seemed to not run enqueued micro-tasks.
See #483 for details
I will move the tests around, as they were used to just verify the original issue. Posting the draft here.
=> Fix for #483 and jestjs/jest#14549

.github/workflows/main.yml, .min-wd, mochify.webdriver.js, package-lock.json, package.json, test/fake-timers-test.js
I'm working on a rewrite of mochify which aims to solve #380, is more modular and works with any bundler.
The current mochify implementation is dated and does not support the latest webdriver protocols.
The new mochify implementation works with pluggable drivers. The `@mochify/driver-webdriver` uses the official `webdriver` module internally.
~~Interestingly, this successfully runs tests in Safari (although there are failing tests), but I'm having trouble running tests in Firefox and Edge.~~
New Mochify development happens on the `rewrite` branch here: https://github.com/mantoni/mochify.js/tree/rewrite
=> New mochify

README.md
Mochify became an org with the rewrite and the description was still referring to PhantomJS.
=> Fix link to Mochify and adjust description

src/fake-timers-src.js, test/fake-timers-test.js, test/issue-1852-test.js, test/issue-2449-test.js, test/issue-59-test.js
fix #490
This makes FakeTimers stricter by failing when trying to fake
a timer or object that is not present on the (chosen) global object.
To make transitioning easier, we provide a flag to revert to the
behavior where missing timers were (mostly) ignored.
See #490
=> Fail when a timer is not available in the context

README.md, src/fake-timers-src.js, test/fake-timers-test.js
Fix issue #469 by implementing promise-based wrappers around setTimeout, setImmediate, and setInterval.
This PR takes a similar approach to #467 by @swenzel-arc of detecting the availability of the `timers/promises` module by attempting to import it and then overwriting the functions on the import object, which should be the same object users have, given they do not mess with the module cache. Like the aforementioned PR, the functions are only overwritten when calling `install()` on the `globalObject`.
* When aborting a timer using an `AbortSignal`, the error thrown is not the same as the one thrown by node. This is due to the `AbortError` error being publicly available. See this [issue](https://github.com/nodejs/node/issues/38361).
* This PR does not touch …
=> Add support for timers/promises module from nodejs

src/fake-timers-src.js, test/fake-timers-test.js
Fix abort event listener leak discussed in #495 by adding `abortListenerMap` to keep track of active abort listeners.
The leak is fixed by adding a map with listener functions as keys and the abort signals as values. During uninstall it iterates over the map and removes the listeners. If a timer is aborted or finishes on its own the listener signal pair will be removed from the map.
=> Fix listener leak for timers/promises

integration-test/fake-clock-integration-test.js, src/fake-timers-src.js, test/fake-timers-test.js, test/issue-437-test.js
Fix issue #437 by creating ClockDate as JS class and extending it from NativeDate
Why I did this way: 
* In initinial solution (creating `ClockDate` by JS function) `ClockDate` can't be correct instance to extend from it. That's why I replaced function on class. And it resolved my problem.
* Mechanics of call `Date()` without `new` keyword I solved by using `Proxy` instance.
* Also in my solution removed an `mirrorDateProperties` function. It's not needed any more.
But I had some troubles with tests:
* I skiped [this test](https://github.com/sinonjs/fake-timers/blob/main/test/fake-timers-test.js#L3106-3117), because I didn't understand what it checks and how it should be now
* I skiped [an other test](https://github.com/sinonjs/fake-timers/blob/main/test/fake-timers-test.js#L3224-3226), …
=> fix: save methods of children Date instance (#437)

RELEASE.md, src/fake-timers-src.js, test/fake-timers-test.js
- **Fix a mistake in release doc**
- **fix: Support performance.measure+mark**
=> Support performance.measure+mark

src/fake-timers-src.js, test/fake-timers-test.js
The output when just inheriting was
function() { [native code] }
vs
function Date() { [native code] }
in the real Date object.
I had to make a choice between having the same function identity and function output and opted for the latter,
since that is what the mother sinon project targets.
=> Fix toString() output

src/fake-timers-src.js, test/fake-timers-test.js
Fix issue #504 by utilizing the well known symbol `Symbol.hasInstance`
to customise the default behavior of the `instanceof` operator.
Refs
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/hasInstance
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof
=> fix #504: make instances of original Date pass as instances of the fake Date

test/issue-504-test.js
=> add unit test for issue#504

src/fake-timers-src.js, test/fake-timers-test.js
Fixes #511 (fix for #510) no longer working after the clock had been installed and global `Date` assigned to the fake.
Once `ClockDateProxy` was installed to global `Date` (to my surprise) the constructor reference on it was 'updated' to point to `ClockDateProxy`.
Thanks again for the help!
=> Fix constructor-based checks for fake Date no longer pass after installing

src/fake-timers-src.js, test/fake-timers-test.js
Fixes sinon.match / samsam equality checks failing between `Date` and fake dates.
Ran into another small issue with the constructor: samsam's `deepEqual` [checks the number](https://github.com/sinonjs/samsam/blob/1b141a7cb9d54b0d8a1f20812c2db4bc1f1e53a3/lib/deep-equal.js#L154) of properties on the object, and the constructor [should not be enumerable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor) so there should be 0 keys, but fake Dates had one now.
=> Ensure checks based Object.keys length pass for fake Dates

src/fake-timers-src.js, test/fake-timers-test.js
Fixes #514
Return valid value for `performance.timeOrigin` instead of `NOOP`. This fixes an issue in tests that depend on `performance.timeOrigin` having a valid value.
See #514
Set `performance.timeOrigin` to a dummy value. I'm not sure if 0 is better than setting the value to `clock.now`. When testing `performance.timeOrigin` in Chrome Console I can see that the value is set to the timestamp when the window was opened:
```
> globalThis.performance.timeOrigin
1733227796841
```
There is further information in MDS docs on how the value is supposed to be set: https://developer.mozilla.org/en-US/docs/Web/API/Performance/timeOrigin#value
=> fix: return fake version for `performance.timeOrigin`

src/fake-timers-src.js, test/issue-516-test.js
This PR is supposed to fix #516. It should make fake-times a bit more resilient to prototype poisoning occurring directly on `Intl`. That said it does not handle deeper prototype breakings.
=> fix: Resilient to prototype pollution of Intl

README.md, src/fake-timers-src.js, test/fake-timers-test.js
This adds a new mode for automatically advancing time that moves more quickly than the existing shouldAdvanceTime, which uses real time. It also adds the ability to modify the initial values that were used for shouldAdvanceTime and advanceTimeDelta. `shouldAdvanceTime` is useful in some situations, but is not useful for solving the problem that testers usually install mock clocks for (to speed up time).
Testing with mock clocks can often turn into a real struggle when dealing with situations where some work in the test is truly async and other work is captured by the mock clock.
In addition, when using mock clocks, testers are always forced to write tests with intimate knowledge of when the mock clock needs to be ticked. Oftentimes, the purpose of using a mock clock is to speed up the …
=> feat: Add additional auto advance time controls

README.md
I had copied my implementation from jest into sinon. Sorry for missing this.
=> docs: Update `setTickMode` docs to mention sinon APIs, not jest
