.travis.yml
Also set `sudo: false` to allow Travis to use VM with much faster startup (and probably
much smaller use of resources)
=> Update travis to use node@0.12

Readme.md, lolex.js, package.json, src/lolex.js, test/lolex-test.js
Basically #29 rebased due to master being changed after merge.
=> Update README and code descriptions

.travis.yml
=> Update .travis.yml to run tests in node 5 also

package.json, test/lolex-test.js
Can no longer push the commit made by NPM directly to the repo, so must go through a PR...
=> 1.5.0 and rebased #51

AUTHORS, History.md, RELEASE.md, package.json, test/lolex-test.js
Improvements to the build process based on that of Sinon.JS.
Adds a changelog and a contributor overview.
Also ensures the bundle is updated before publishing.
=> Build process improvements

src/lolex-src.js, test/lolex-test.js
This is just @rogierschouten's work rebased (and squashed the two first commits into one). Look into #62 and #59 for details - nothing new.
=> PR #62 repacked (fixes #59)

AUTHORS, History.md, RELEASE.md, lolex.js, package.json
Includes a few fixes and some additions to the release document (like needing to create a PR such as this).
=> Release of 1.5.1

lolex.js, src/lolex-src.js
Browserify already adds a wrapper function if the use of `global` is detected. This will fix the issue we're having with browserifying Sinon.JS.
=> Remove wrapper function

Readme.md
=> Removed extra comma in setImmediate's description

package.json
Failed the Bithound builds, preventing merges
=> Update old dependencies

Readme.md
Fixes https://github.com/sinonjs/lolex/issues/109
=> Update documentation for lolex 2

src/lolex-src.js, test/lolex-test.js
Fixes https://github.com/sinonjs/lolex/issues/110
=> process.hrtime timer run fix

src/lolex-src.js
No point in polyfilling keys in one place and not using the polyfill later - either we remove the polyfill or we call it :)
=> Use added `keys`

src/lolex-src.js, test/lolex-test.js
Add support for nextTick with microtask semantics.
Microtask semantics follow Node behavior and ECMAScript's EnqueueJob
description. Microtasks are run between every "I/O" operation (timers
in this case).
This also paves the path for mocking promises. Since after this doing
and overriding Promise.prototype.then both promises supplied by the
platform and promises supplied by user libraries can be hooked on.
=> Add support for process.nextTick

package.json
Adds precommit and prepublish hooks after seeing linting errors creep in through the PRs.
=> Commit hooks

package.json
=> add module entry point

src/lolex-src.js, test/lolex-test.js
Fixes: https://github.com/sinonjs/lolex/issues/134
Uses the proposed solution of Math.max
=> fix negative timeout bug

src/lolex-src.js, test/lolex-test.js
Fixes #138
Signed-off-by: Peter A. Bigot <pab@pabigot.com>
=> determine timer type on construction

src/lolex-src.js, test/lolex-test.js
Fixes: https://github.com/sinonjs/lolex/issues/84
=> Return timers on uninstall

package-lock.json, package.json
=> Update Mocha to 4.0.1

Readme.md
Typo in the docs, implementation is correct
=> clearAnimationFrame is cancelAnimationFrame

Readme.md
=> Use SVG Travis Icon in README

Readme.md, src/lolex-src.js, test/lolex-test.js
Fixes https://github.com/sinonjs/lolex/issues/147 
cc @SimenB @fatso83
=> Expose run microtasks

.travis.yml
Update Node.js versions to latest lts as described in https://github.com/nodejs/Release
=> Update Node.js versions

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Fix typos in github issue and PR templates
=> fix: typos in github templates

Readme.md, src/lolex-src.js, test/lolex-test.js
See #161 for justification. Fixes #161
=> Clear microtick jobs and set now to 0 in reset

src/lolex-src.js
Fixes https://github.com/sinonjs/lolex/issues/171#issuecomment-389487264 since apparently some environments expose `global.performance` but not `global.Performance`. 
Guard checking performance with `global.Performance`.
=> Check Performance exists before using it

Readme.md
Reflect changes of https://github.com/sinonjs/lolex/pull/184
=> fix reset docs

src/lolex-src.js, test/lolex-test.js
=> fix: reset high resolution timer on clock.reset

package-lock.json
See https://nvd.nist.gov/vuln/detail/CVE-2018-16472
=> Upgrade cached-path-relative

Readme.md
=> docs: requestIdleCallback and cancelIdleCallback added to Readme

src/lolex-src.js, test/lolex-test.js
=> fix: count microtasks in countTimers

src/lolex-src.js, test/lolex-test.js
Fixes #235.
I didn't think it was relevant to mention this in the documentation.
=> Support hrtime.bigint()

src/lolex-src.js, test/lolex-test.js
=> Fix setSystemTime affects hrtime if its called multiple times.

package-lock.json, package.json, src/lolex-src.js
Use `global` from commons for Worker compatibility.
This is needed for https://github.com/sinonjs/sinon/pull/2175.
=> Use global from `@sinonjs/commons`

README.md
Version 2.0 was released 3 years ago so there is no need to add focus on the fact that some feature was added at that moment
=> Remove notes on v2.0 from the docs

.circleci/config.yml
And run tests in Node 14, which is the current LTS release
=> Drop Node 8

.circleci/config.yml, .eslintrc.yaml, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .prettierignore, .prettierrc, CODE_OF_CONDUCT.md, README.md, RELEASE.md, integration-test/fake-clock-integration-test.js, package-lock.json, package.json, src/fake-timers-src.js, test/fake-timers-test.js
We're trying get all the `@sinonjs/*` projects on the same page with `prettier`, so we can reduce the maintenance burden. This PR is part of that effort.
=> Use prettier@2

src/fake-timers-src.js
Make generated TypeScript tyoe definitions usable. My goal was to make the types usable in a typical situation:
```ts
import { install, Clock } from '@sinonjs/fake-timers';
let clock: Clock;
beforeEach(() => {
clock = install();
});
afterEach(() => {
clock.uninstall();
});
```
My goal was not to provide perfect types. I.e. `any` and `Function` types are used and many docs are missing, because I’m not 100% sure what everything does.
Closes #356
I added the `Clock` type definition. This is returned by both `createClock()` and `install()`.
---
To aid reviewers, this is the generated `.d.ts` file after this merge request:
```ts
export type Clock = {
now: number;
timeouts: any;
Date: any;
loopLimit: number;
requestIdleCallback: (func: Function, timeout: number) => any;
cancelIdleCallback: …
```
=> Fix usage with TypeScript

package-lock.json, package.json
This PR upgrades test dependencies and transitive dependencies.
=> Upgrade test dependencies

package.json, src/fake-timers-src.js, test/fake-timers-test.js
Use one of the simpler ES2015+ features.
=> Const for var

.eslintrc.yaml
See https://github.com/sinonjs/fake-timers/pull/401#discussion_r713692379
=> chore: enforce semicolons via ESLint

.github/workflows/main.yml
See https://github.com/actions/setup-node/blob/main/README.md#caching-packages-dependencies
=> chore(ci): use builtin dependency caching

README.md
Fixes #343, small clarification on how to use fake-timers in async environments
=> Clarify async usage

.github/workflows/main.yml
=> chore: test on node 17

package-lock.json, test/fake-timers-test.js
Fix skipping of tests. Return early instead of executing and showing as pending.
=> Fix skip tests

package-lock.json, package.json, test/fake-timers-test.js
That makes ES2017 support explicit
=> Prefer @sinonjs/commons@2

.github/workflows/main.yml
=> Run CI tests in node 19

.github/workflows/main.yml
=> chore: update gh actions

.husky/pre-commit
See https://github.com/sinonjs/fake-timers/pull/440/files#r1032069294
https://typicode.github.io/husky/#/?id=locally-installed-binaries
=> chore: use npx in pre-commit hook

.github/workflows/main.yml
Verify build works using Node 20
=> Build using Node 20 LTS

.github/workflows/main.yml, scripts/test-watch-mode-works.sh, test/fake-timers-test.js
- Fix tests breaking in watch mode
- Script that can detect failures in watch mode
- Setup test for watch mode on Github Actions
=> fix watch mode

.husky/pre-commit, package-lock.json, package.json, src/fake-timers-src.js, test/fake-timers-test.js
- **Upgrade dependencies**
- **Remove lines due to future breaking change in Husky**
=> upgrade deps

src/fake-timers-src.js, test/fake-timers-test.js
Fixes #510 by mirroring the constructor prop of Date objects
=> Ensure checks based on the constructor property passes for fake Dates

.github/ISSUE_TEMPLATE.md, .github/workflows/main.yml, .tool-versions, CODE_OF_CONDUCT.md, README.md, package-lock.json, package.json
Upgrade versions before release
=> Upgrade versions
